sudo: false

language: bash

env:
  global:
    - release_stamp="REL$(date +%Y%m%d%H%M%S)"

services:
  - docker

cache:
  apt: true
  pip: true
  bundler: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm
    - $HOME/docker
    - $GEM_HOME

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_install:
  - curl https://raw.githubusercontent.com/hipages/travis-tools/master/docker/before_install.sh | sudo bash
  - mkdir -p ${HOME}/.ssh && openssl aes-256-cbc -K $encrypted_51f71ad0bde3_key -iv $encrypted_51f71ad0bde3_iv -in build/id_rsa_deploykey.enc -out ${HOME}/.ssh/id_rsa -d && chmod 400 ${HOME}/.ssh/id_rsa

install:
  - curl https://raw.githubusercontent.com/hipages/travis-tools/master/docker/install.sh | sudo bash

script:
  - curl https://raw.githubusercontent.com/hipages/travis-tools/master/docker/script.sh | sudo bash

after_success:
  - curl https://raw.githubusercontent.com/hipages/travis-tools/master/docker/success.sh | sudo bash

branches:
  except:
    - /^REL\d+/

