sudo: false

bash: ["4.4"]
node_js: ["5.5"]
python: ["3.4"]
go: ["1.8"]

services:
  - docker

cache:
  apt: true
  pip: true
  bundler: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm
    - $HOME/docker
    - $GEM_HOME

addons:
  apt:
    packages:
      - ca-certificates
      - python-dev
      - shellcheck

before_install:
  - source <(curl -sSL https://raw.githubusercontent.com/hipages/travis-tools/master/docker/before_install.sh)
  - mkdir -p ${HOME}/.ssh && openssl aes-256-cbc -K $encrypted_51f71ad0bde3_key -iv $encrypted_51f71ad0bde3_iv -in build/id_rsa_deploykey.enc -out ${HOME}/.ssh/id_rsa -d && chmod 400 ${HOME}/.ssh/id_rsa

install:
  - source <(curl -sSL https://raw.githubusercontent.com/hipages/travis-tools/master/docker/install.sh)

script:
  - source <(curl -sSL https://raw.githubusercontent.com/hipages/travis-tools/master/docker/script.sh)

after_success:
  - source <(curl -sSL https://raw.githubusercontent.com/hipages/travis-tools/master/docker/after_success.sh)

branches:
  except:
    - /^REL\d+/
    - /^BRANCH-.*$/

